### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: random_maps_together/widget.xml

### ISSUE THREAD

**Issue by SecretUnicorn** [thexivn/RandomMapTogether#1]
I couldn't figure out how to install your plugin?
I cloned the repo, ran setup.py and added this to my apps.py
`'it.thexivn.random_maps_together',`

but now it produces this error
```
ERROR    [default][pyplanet.core.instance] random_maps_together/widget.xml
Traceback (most recent call last):
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/jinja2/loaders.py", line 365, in get_loader
    loader = self.mapping[prefix]
KeyError: 'random_maps_together'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/pyplanet/core/instance.py", line 108, in start
    self.loop.run_until_complete(self._start())
  File "/home/nicklas/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/pyplanet/core/instance.py", line 166, in _start
    await self.apps.init()                              # Initiate apps
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/pyplanet/apps/apps.py", line 178, in init
    await app.on_init()
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/random_maps_together-0.0.4-py3.7.egg/it/thexivn/random_maps_together/__init__.py", line 38, in on_init
    await self.rmt_game.on_init()
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/random_maps_together-0.0.4-py3.7.egg/it/thexivn/random_maps_together/RMTGame.py", line 61, in on_init
    await self._score_ui.display()
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/pyplanet/views/generics/widget.py", line 67, in display
    return await super().display(**kwargs)
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/pyplanet/views/template.py", line 160, in display
    return await super().display(player_logins, **kwargs)
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/pyplanet/core/ui/components/manialink.py", line 121, in display
    return await self.manager.send(self, player_logins, **kwargs)
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/pyplanet/core/ui/__init__.py", line 106, in send
    if await manialink.get_template() and not manialink.body:
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/pyplanet/views/template.py", line 99, in get_template
    return await load_template(self.template_name)
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/pyplanet/core/ui/template.py", line 8, in load_template
    return Template(file)
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/pyplanet/core/ui/template.py", line 48, in __init__
    self.template = self.env.get_template(file)
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/jinja2/loaders.py", line 381, in load
    loader, local_name = self.get_loader(name)
  File "/home/nicklas/.pyenv/versions/trackmania/lib/python3.7/site-packages/jinja2/loaders.py", line 367, in get_loader
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: random_maps_together/widget.xml
```

**Comment by thexivn** [comment]
added the `templates` folder inside the `MANIFEST` and `setup.py`. Now it  should copy correctly the folder when the APP is installed
